### PR TITLE
sql/postgres: support schema comments

### LINKED ISSUE #1819: Missing schema comment (on Postgres)
When setting up as

```sql
CREATE SCHEMA "foo";
COMMENT ON SCHEMA "foo" IS 'bar';
```

I get from `atlas schema inspect`

```
schema "foo" {
}
schema "public" {
}
```

Am I wrong to expect something along the lines of

```
schema "foo" {
  comment = "bar"
}
schema "public" {
}
```

(using atlas version v0.12.1-17d97d4-canary)?

### PR DESCRIPTION
**Pull request by a8m**
Fixed #1819

### CODE REVIEW

File: sql/postgres/diff_test.go [hunk 1]
```diff
@@ -502,6 +502,26 @@ func TestDiff_SchemaDiff(t *testing.T) {
...
+
+	// Add comment.
+	from, to = schema.New("public"), schema.New("public").SetComment("comment")
+	changes, err = drv.SchemaDiff(from, to)
+	require.NoError(t, err)
+	require.EqualValues(t, []schema.Change{
+		&schema.ModifySchema{S: to, Changes: schema.Changes{&schema.AddAttr{A: &schema.Comment{Text: "comment"}}}},
+	}, changes)
+	// Modify comment.
+	from.SetComment("boring")
```
Comment (masseelch) [inline sql/postgres/diff_test.go:514]: 🤔😁

**Review by masseelch — APPROVED** [review]
