### PR TITLE
sql/mysql: add support for float and decimal unsigned attribute

### LINKED ISSUE #545: MySQL - Atlas fails to inpect schema when a column is specified as an unsigned float
It seems that when you create a column in mysql with an unsigned float, Atlas cannot parse its precision in sql/mysql/convert.go and throws a lovely error message like below:

Error: mysql: parse precision "unsigned"

### PR DESCRIPTION
**Pull request by masseelch**
Fix #545

### CODE REVIEW

**Review by a8m — APPROVED** [review]
Beast! 🥳

File: sql/mysql/convert.go [hunk 1]
```diff
@@ -60,6 +63,9 @@ func FormatType(t schema.Type) (string, error) {
 		if f == TypeFloat && t.Precision > 24 || f == TypeReal {
 			f = TypeDouble
 		}
+		if t.Unsigned {
+			f += " unsigned"
```
Comment (yonidavidson) [inline sql/mysql/convert.go:67]: don't you have another way to add words without using "space" as part of the string?
