### PR TITLE
sql/mysql: inspect: support fractional seconds precision in timestamp…

### LINKED ISSUE #471: Support schema inspect for Mysql table with column "Timestamp/Datetime default on update"
We have a column that is in Datetime type and has the [default on update definition](https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html). For example:

```
CREATE TABLE `foo` (
 `id`			INT,
 `update_time`	DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)

  PRIMARY KEY (`id`),
)
```

When I try to inspect the schema, I got the following error: 
```
atlas schema inspect -d "mysql://root:secret@tcp(localhost:12334)/my_database"
Error: mysql: unknown attribute "on update current_timestamp(6)"
```

Mysql version: 5.7.35

Atlas version: 
```
atlas CLI version v0.3.1
https://github.com/ariga/atlas/releases/tag/v0.3.1
```

### PR DESCRIPTION
**Pull request by masseelch**
… type, its default and on update clause

Fix #471

### CODE REVIEW

File: sql/mysql/inspect.go [hunk 1]
```diff
@@ -514,6 +516,8 @@ func (i *inspect) createStmt(ctx context.Context, t *schema.Table) error {
 	return nil
 }
 
+var crrTsDefReg = regexp.MustCompile(`(?i)^current_timestamp(?:\(\d?\))?$`)
```
Comment (a8m) [inline sql/mysql/inspect.go:519]:
```suggestion
var reCurrTS = regexp.MustCompile(`(?i)^current_timestamp(?:\(\d?\))?$`)
```

**Review by a8m — APPROVED** [review]
Looks goooooood ❤️
